### ISSUE TITLE
RoR webapp doesn't send emails anymore when a message is sent through the app

### ISSUE THREAD

**Issue by yvescreemers** [sendgrid/sendgrid-ruby#176]
#### Issue Summary

Normally, when a user sent a message an email was sent to the person that they received a new message. 

Suddenly the emailsystem stopped working. No emails to see in the 'activity' tab. I already tried connecting to the port (587) and it works find. The email I send via this port even showed up in the 'activity' feed. 

Now my questions is: how can I see where it goes wrong?

Thanks!

#### Technical details:

* Ruby Version: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

**Comment by thinkingserious** [comment]
Hello @yvescreemers,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
