### ISSUE TITLE
Create a tutorial to deploy a simple Hello Email app on Heroku with Ruby using this SDK

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-ruby#183]
Create a tutorial that explains how to create a simple Hello Email app and [deploy to Heroku](https://devcenter.heroku.com/articles/heroku-button).

The example should utilize best practices for storing credentials. By the end of the tutorial, the user should be able to send an email using their deployed app.

Please add the tutorial to USE_CASES.md.

**Comment by architapatelis** [comment]
@thinkingserious I will work on this example before I work on the Google App Engine example

**Comment by thinkingserious** [comment]
Thank you @architapatelis!

**Comment by architapatelis** [comment]
@thinkingserious sorry, it took me sometime to work on this. I have finished writing out the tutorial - https://github.com/architapatelis/sendgrid_heroku 

Can you have a look at the link above, if everything looks good to you, I will fork this repo, add the instructions to `USE_CASES.md` and then create a pull request. 

If you need me to make any changes let me know. The instructions are in-depth, I am a student and I started learning coding a few months ago, so I wrote the instructions for someone who has very little experience. It might be too much for developers like yourself, so if there are parts you want me to delete, I can do that. Let me know when you can. thanks!

**Comment by architapatelis** [comment]
@thinkingserious sorry it took me a while to finish writing the tutorial. But I am done, you can have a look at the README.md file here - https://github.com/architapatelis/sendgrid_heroku

I am a student, and I just started learning how to code a few months ago. So, I wrote the tutorial for people with very little experience. I realize that it might be too detailed for developers like yourself. Let me know if there is anything that you want me to delete. I just want you to have a look at it before I create a pull request, since it's so long you might not want it in the `USE_CASES.md` file. 

Let me know when you can. thanks!

**Comment by childish-sambino** [comment]
Closing as this feels like more of a blog post than library documentation and use cases.
