### ISSUE TITLE
Multiple recipients 

### ISSUE THREAD

**Issue by sithara** [sendgrid/sendgrid-ruby#308]
Could you please provide an example on how to add multiple recipients to the below code

```
require 'sendgrid-ruby'
include SendGrid

from = Email.new(email: 'test@example.com')
to = Email.new(email: 'test@example.com')
subject = 'Sending with SendGrid is Fun'
content = Content.new(type: 'text/plain', value: 'and easy to do anywhere, even with Ruby')
mail = Mail.new(from, subject, to, content)

sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
response = sg.client.mail._('send').post(request_body: mail.to_json)
puts response.status_code
puts response.body
puts response.parsed_body
puts response.headers
```

Thanks much

**Comment by haffla** [comment]
You should use Personalizations for this.

Example: https://github.com/sendgrid/sendgrid-ruby/blob/master/examples/helpers/mail/example.rb#L26

You can see that `Personalization` class has a method `add_to`.

**Comment by haffla** [comment]
@toadkicker I believe that emails using transactional templates can only be sent to one recipient at a time. You need one API call per recipient.

**Comment by toadkicker** [comment]
Yep that is what I figured out as well. The Personalization.add_to method adds multiple recipients but provides no way to access its attributes in a transactional email template.

**Comment by thinkingserious** [comment]
Thanks for helping out @haffla!

@toadkicker,

You can have multiple personalizations per email, but only one transactional template per API call to `mail/send`.  Have you been able to implement your use case?

With Best Regards,

Elmer

**Comment by toadkicker** [comment]
Yes unfortunately I am making multiple API calls. It is a small list so it should be fine.

Thanks,

Todd

**Comment by thinkingserious** [comment]
Thanks for the follow up @toadkicker!

Just to be clear, what you would like to do is set multiple templates within the same API call?

**Comment by toadkicker** [comment]
Use the same template ID but send an array of users and have it still be personalized.

**Comment by haffla** [comment]
@toadkicker it's actually possible to do that.

```
data = {
  from: "you@example.com",
  template_id: "YOUR_TEMPLATE_ID",
  personalizations: [
    {
      to: [
        {
          email: "one@example.com"
        }
      ],
      dynamic_template_data: {
        name: "One"
      }
    },
    {
      to: [
        {
          email: "two@example.com"
        }
      ],
      dynamic_template_data: {
        name: "Two"
      }
    }
  ]
}

sg.client.mail._('send').post(request_body: data)

```

This will send two individual emails with one API call. Using sendgrid helpers as in your case:

```
admin_emails.each do |email|
  personalization = Personalization.new
  personalization.add_to(Email.new(email))
  personalization.add_dynamic_template_data(
    "admin": email[:name].gsub(/&nbsp;/, ' '),
    "user": {
      "full_name": @user.full_name.gsub(/&nbsp;/, ' '),
      "company": {
        "name": @user.company.name
      }
    },
    "claims": @claims
  )
  @mail.add_personalization(personalization)
end
```

**Comment by haffla** [comment]
I think `add_dynamic_template_data` is an unfortunate method name. It suggests that you can *add* data to a personalization just in the same way that you add an email to `to` using `add_to`. `to` is an array, but `dynamic_template_data` is a hash/object.

It should have been `personalization.dynamic_template_data = data`.

**Comment by thinkingserious** [comment]
That's a good point @haffla,

Perhaps we can use the method you suggest and deprecate the current method. Would you be up for a [Hacktoberfest](https://dx.sendgrid.com/hacktoberfest) PR?

With Best Regards,

Elmer

**Comment by haffla** [comment]
Yeah I am. Is the change in the API acceptable for you? I know it's not released yet but I think many people are already using an unreleased version.

**Comment by andrew-koster-** [comment]
It's **_REALLY WEIRD_** that I have to:

- Create this whole Personalizations object, call a bunch of methods on it, and add it back into the Mail object.
- Specify the `to` address in the `to` parameter of `Mail.new` **and** in the `add_to` method of the Personalizations object.
- Write a bunch of wrapper code with type checks and such, in order to keep this boilerplate junk out of my business logic.

All just to perform the extremely common operation of sending an email to more than one address.

**Comment by childish-sambino** [comment]
@andrew-koster- Note that _Specify the to address in the to parameter of Mail.new_ is not required. Creating the personalization and using `add_to` are. This is a reflection of the API, but PRs to simplify this are welcome in the client (other clients simplify this some).

@haffla I disagree about the naming of `add_dynamic_template_data`. It allows for adding dynamic template data by merging it with any existing dynamic template data, effectively adding it. For that reason, I'm gonna close the PR and this issue since it seems there is an example of sending to multiple recipients.
