### ISSUE TITLE
No email validation - leads to wildcard deletion in web ui

### ISSUE THREAD

**Issue by swallenfriedman** [sendgrid/sendgrid-ruby#309]
#### Issue Summary

Hi All,

We've noticed an issue that when creating entries in the global unsubscribes list via the API, there is no validation done that the email addresses are being added. This wouldn't be a problem except it appears that the API does not allow deletion of invalid email addresses and subsequently deleting the invalid email address from the web UI has some nasty side effects (namely, deleting an empty email record from the web UI ends up deleting _all_ emails from that unsubscribe list).

#### Steps to Reproduce

1. Create an empty email in the unsubscribe list:
```
SendGrid::API.new(api_key: api_key).client.asm.suppressions.global.post(request_body: { "recipient_emails" => [""] })
```
2. Observe that this empty record is created either through web UI or `SendGrid::API.new(api_key: api_key).client.suppression.unsubscribes.get`
3. Create other valid email entries
4. Delete empty email entry via web ui

We would expect either:
* The creation of an invalid entry should fail
* The deletion from the UI of an empty entry should not delete all records

#### Technical details:

* sendgrid-ruby (5.2.0)
* Ruby Version (2.3.4)

**Comment by thinkingserious** [comment]
Hello @swallenfriedman,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
