### ISSUE TITLE
How to update subusers?

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [sendgrid/sendgrid-ruby#435]
### Issue Summary
How can I update subusers with the ruby sendgrid gem?
You only show create and delete actions in your examples here: https://github.com/sendgrid/sendgrid-ruby/blob/main/examples/subusers/subusers.rb

When I try to use put or patch, it just gives me an "not found" error back?

**Comment by childish-sambino** [comment]
I'm not seeing this as being possible using the API: https://sendgrid.api-docs.io/v3.0/subusers-api/

Recommend contacting support for more details.

**Comment by thinkingserious** [comment]
Hello @h0jeZvgoxFepBQ2C,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
