### ISSUE TITLE
How to add/remove contacts to a list via new marketing API?

### ISSUE THREAD

**Issue by netwire88** [sendgrid/sendgrid-ruby#456]
There doesn't seem to be any documentation on how to add/remove contacts to a list via the new marketing API? Is there a gem wrapper around this https://sendgrid.api-docs.io/v3.0/lists/remove-contacts-from-a-list?

**Comment by rickychilcott** [comment]
#391 might be helpful to you. This does need better documentation

**Comment by netwire88** [comment]
Thanks @rickychilcott , I read through that, but the example is how to create a contact & add it to a list at the same time. I'm trying to figure out how to add/remove contacts to/from lists without updating contact info. Any ideas?

**Comment by rickychilcott** [comment]
If you don't want to 

Adding a user to a list without changing anything else about that should be something like:

```ruby
contacts = [{ email: "abc@1234.com"}]
list_ids = ["abcd"]
response = sg.client.marketing.contacts.put(request_body: {list_ids: list_ids, contacts: contacts})
```
Note, if the email address does not exist, it will create a new contact.

Regarding deleting a contact from a list, I havent' done it myself.

The code you wrote does look close (e.g. `sg.client.marketing.lists._(list_id).delete(contact_ids: contact_id)`). 

But since that URL you linked to is `DELETE /marketing/lists/{id}/contacts` does the following work: 

```ruby
sg.client.marketing.lists._(list_id).contacts.delete(contact_ids: contact_id)
```

**Comment by netwire88** [comment]
Thanks @rickychilcott , great ideas!

**Comment by thinkingserious** [comment]
Please be sure to vote on [this issue](https://github.com/sendgrid/sendgrid-ruby/issues/391) to help move the priority up. Thanks!
