### ISSUE TITLE
bundle install fails due to listen gem

### ISSUE THREAD

**Issue by bentona** [sendgrid/sendgrid-ruby#64]
```
Installing listen 3.1.5

Gem::InstallError: listen requires Ruby version >= 2.2.3, ~> 2.2.
...
An error occurred while installing listen (3.1.5), and Bundler cannot continue.
Make sure that `gem install listen -v '3.1.5'` succeeds before bundling.
```

**Comment by bentona** [comment]
https://travis-ci.org/sendgrid/sendgrid-ruby/jobs/129869277

**Comment by thinkingserious** [comment]
Hello @bentona,

Thanks for taking the time to report this to us!

From what I've seen, it looks like this is a Travis issue (I've tried several Stack Overflow suggestions to no avail). I've seen this happen before with Travis (most recently with C#) and usually they will push up some fix and the issue will go away. 

That said, I don't plan to dig any deeper, since this library will be replaced in a few weeks with this one: https://github.com/sendgrid/sendgrid-ruby/tree/v3beta and I'm not having any troubles with the tests there.

With Best Regards,

Elmer
