### ISSUE TITLE
SendGrid fails when a name contains comma character

### ISSUE THREAD

**Issue by thesmart** [sendgrid/sendgrid-ruby#77]
#### Issue Summary

When names include a comma character "," the email is dropped by SendGrid due to reason "Invalid", because it interprets the wrong email address.  In the Activity view, SendGrid appears to have tried to send to part of the name field instead of the email field, indicating the the "comma" was used even though it is in part of a string.

#### Steps to Reproduce

Here is the repro call to `SendGrid::API`:
```
    params = {
      "template_id" => "88dd23ff-f322-40a4-b646-1144c43340a8",
      "subject" => "Forgot your password?",
      "personalizations" =>
        [
          {
            "to" =>
              [
                {
                  "email" => "smart+test@figma.com",
                  "name" => "Figma, Inc."
                }
              ],
            "substitutions" =>
              {
                "{{URL_ESCAPED_VALIDATION_TOKEN}}" => "***REDACTED***",
                "{{URL}}" => "https://www.figma.com",
                "{{SUPPORT_EMAIL}}" => "smart+test@figma.com",
                "{{UNSUBSCRIBE_TOKEN}}" => "***REDACTED***"
              }
          }
        ],
      "tracking_settings" => {
        "click_tracking" => {"enable" => false},
        "open_tracking" => {"enable" => false}
      },
      "content" =>
        [
          {"type" => "text/html", "value" => " "}
        ],
      "from" =>
        {
          "email" => "support@email.figma.com",
          "name" => "Figma"
        }
    }

    response = sendgrid.client.mail._('send').post(request_body: params)
    puts response.to_json
```

The result is a 202, but the email does not get sent because it is rejected due to "Invalid", and the reported email address it tried sending to is "Figma" instead of "smart+test@figma.com".  

Here is the result from `sendgrid.client.suppression.invalid_emails.get`
```
[{\"created\":1468461165,\"email\":\"figma\",\"reason\":\"Invalid address\"}]
```

Are there undocumented rules for names?  Are we supposed to encode them in some way or strip special characters?  Why doesn't your platform do this for us?  Why doesn't your platform reject the request?

#### Technical details:

* sendgrid-ruby Version: sendgrid-ruby 3.0.4
* Ruby Version: 2.3.1

**Comment by thesmart** [comment]
It appears that either a comma or period in the name field will result in an incorrect email address...

**Comment by thesmart** [comment]
![overview_-_sendgrid_documentation___sendgrid](https://cloud.githubusercontent.com/assets/280877/16850940/24760884-49b6-11e6-9138-4c04c781019e.png)

**Comment by thinkingserious** [comment]
@thesmart, please see: https://github.com/sendgrid/sendgrid-csharp/issues/268

I'll add your vote to the issue internally. Thanks!

**Comment by thinkingserious** [comment]
Also, I'll pass this feedback on to the documentation team. Thanks again!

**Comment by thesmart** [comment]
Why doesn't your library handle this though?  The client should help enforce the rules, shouldn't it?

**Comment by thinkingserious** [comment]
@thesmart Agreed, and client side validation is already on our internal roadmap for all our libraries. 

Currently, validation is handled server side. The improvement over v2, is that in v3 there is a [sandbox mode](https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/sandbox_mode.html) so you can test without using email credits.

I'll be creating a public issue soon for client side validation, so that you may vote it up to help it rise in the queue.

Thanks again for the feedback!

**Comment by thinkingserious** [comment]
@thesmart,

Also, I have learned that there is an open ticket to fix the response from the API.

**Comment by thesmart** [comment]
@thinkingserious Thanks! In the interim, is there some rule we can follow or some set of characters I should strip or reject?  Is it just commas? Do I need to use encoded word standard? https://en.wikipedia.org/wiki/MIME#Encoded-Word

I'm not sure how to deal with this other than to stop using the name field all together.  Any details on a work-around would be appreciated!

**Comment by thinkingserious** [comment]
@thesmart,

Commas and semicolons seem to be the only ones currently.

As a workaround, I'd do a try/catch and look for instances of that error. If the error occurs, I'd replace that character with an appropriate one and re-send.

**Comment by thesmart** [comment]
To be clear, no error is returned by the API. I will replace those
character with spaces. Thanks for the help! <3

**Comment by garnold** [comment]
@thinkingserious We were just bitten by this bug too.  What's the status on the [open ticket you referenced](https://github.com/sendgrid/sendgrid-ruby/issues/77#issuecomment-232773309)?

**Comment by thinkingserious** [comment]
@garnold,

The issue is on our backlog for a fix, but there is no release data as of today.

**Comment by garnold** [comment]
@thinkingserious Thanks for the update. I see that it's listed in the "Limitations" section of the API documentation, but it might be better off if it was noted on request parameters.  This one bit us hard.

**Comment by thinkingserious** [comment]
Hello @garnold,

Could you please point me to where you were looking in the documentation? Thanks!

**Comment by garnold** [comment]
Hey @thinkingserious , 

Here's where the documentation talks about not being able to use `;` or `,`:

https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html#-Limitations

Here's where I was reading while implementing our API calls:

https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html#-Request-Body-Parameters

Of course now I see that the Limitations section was directly above the request parameters section, however the table in the request parameters section also includes a "Limitations" column which does not mention the semi-colon/comma issue.

**Comment by thinkingserious** [comment]
Thanks @garnold!

If you click on the down icon next to the name parameter: https://www.screencast.com/t/esT65SKqer3N

Would you suggest that we have all of the descriptions expanded by default?

**Comment by garnold** [comment]
@thinkingserious Well I'll be damned.

For some parameters the limitation is specified without having to expand the description, whereas for others the limitation is hidden until you expand the details.  Consider the `from` and `reply_to` parameters:

https://www.dropbox.com/s/wiw1w7638a01gbt/Screenshot%202017-01-25%2016.24.45.png?dl=0
https://www.dropbox.com/s/i3kcqd9mgqvwaca/Screenshot%202017-01-25%2016.26.33.png?dl=0

Since limitations potentially break things (in the case of semi-colons and commas, silently), I'd prefer to have them front and center without having to expand details, and reserve details for more info (such as base64-encoding attachment content).  Also, it would help if clicking on the entire row expanded details, because the expand/collapse icon at the end of the row is easily overlooked.

**Comment by thinkingserious** [comment]
Thanks @garnold,

This is great feedback, I will pass this along to our documentation team for improvements.

With Best Regards,

Elmer

**Comment by garnold** [comment]
Much appreciated @thinkingserious !

**Comment by jleider** [comment]
I realize I am digging this up from the grave but we also ran into this issue as well. Its great that the documentation was updated with these caveats, but how does that really help? This should be an error condition sent back to the client so that anyone interfacing with the API knows that something is amiss. It is unexpected behavior that SendGrid would simply drop the email and respond to the API client as if everything was fine, that is the real bug.

**Comment by thinkingserious** [comment]
Hi @jleider,

I am passing your feedback along to the product team. Thanks for taking the time to specify the issue in detail!

With Best Regards,

Elmer

**Comment by smithcoin** [comment]
It's 2019, and this is _still_ an issue. Not just for the Ruby client, but for the API.

**Comment by ccurtin** [comment]
It is true that `,` and `;` are not directly available for the `name` parameter but to fix this all we need to do is encode the `name` parameter with `encodeURIComponent(name)`
